const MapEditorData = {
  GRID_COLS: 42,
  GRID_ROWS: 34,
  TILE: 48,

  TILES: [
    { id: 0, name: 'Chão',       emoji: '🟫', color: '#111c11', solid: false },
    { id: 1, name: 'Relva',      emoji: '🌿', color: '#0a1a0a', solid: false },
    { id: 2, name: 'Pedra',      emoji: '🪨', color: '#1a1a1a', solid: false },
    { id: 3, name: 'Água',       emoji: '💧', color: '#0a1220', solid: true  },
    { id: 4, name: 'Ruínas',     emoji: '🏛️', color: '#1c1410', solid: false },
    { id: 5, name: 'Areia',      emoji: '🏜️', color: '#c2a050', solid: false },
    { id: 6, name: 'Lava',       emoji: '🌋', color: '#cc3300', solid: true  },
    { id: 7, name: 'Neve',       emoji: '❄️', color: '#e0e8f0', solid: false },
  ],

  OBJECTS: [
    { id: 'player_spawn',  name: 'Spawn Jogador',   emoji: '🚩', color: '#44ff44', category: 'spawn',  max: 1 },
    { id: 'enemy_spawn',   name: 'Spawn Inimigo',   emoji: '💀', color: '#ff4444', category: 'spawn',  max: 8 },
    { id: 'boss_spawn',    name: 'Spawn Boss',      emoji: '👹', color: '#ff00ff', category: 'spawn',  max: 1 },
    { id: 'waypoint',      name: 'Checkpoint',      emoji: '🏁', color: '#ffff00', category: 'spawn',  max: 4 },
    { id: 'crate',         name: 'Caixa',           emoji: '📦', color: '#8B6914', category: 'object', max: 99, solid: true },
    { id: 'barrel',        name: 'Barril',          emoji: '🛢️', color: '#6B4226', category: 'object', max: 99, solid: true },
    { id: 'bone',          name: 'Osso',            emoji: '🦴', color: '#d4c8a0', category: 'object', max: 99, solid: false },
    { id: 'bush',          name: 'Arbusto',         emoji: '🌾', color: '#2d7a1e', category: 'object', max: 99, solid: false },
    { id: 'cactus',        name: 'Cacto',           emoji: '🌵', color: '#2d8a2e', category: 'object', max: 99, solid: true },
    { id: 'log',           name: 'Tronco',          emoji: '🪵', color: '#5c3a1e', category: 'object', max: 99, solid: true },
    { id: 'chest',         name: 'Baú',             emoji: '🧰', color: '#c8a84a', category: 'loot',   max: 5,  solid: true },
    { id: 'health_pack',   name: 'Curativo',        emoji: '❤️', color: '#ff4444', category: 'loot',   max: 5,  solid: false },
    { id: 'power_pack',    name: 'Energia',         emoji: '⚡', color: '#4488ff', category: 'loot',   max: 5,  solid: false },
    { id: 'torch',         name: 'Tocha',           emoji: '🔥', color: '#ff8800', category: 'deco',   max: 99, solid: false },
    { id: 'skull',         name: 'Crânio',          emoji: '💀', color: '#cccccc', category: 'deco',   max: 99, solid: false },
    { id: 'flag',          name: 'Bandeira',        emoji: '🚩', color: '#ff2222', category: 'deco',   max: 10, solid: false },
    { id: 'fence',         name: 'Cerca',           emoji: '🪵', color: '#8B6914', category: 'deco',   max: 99, solid: true },
    { id: 'campfire',      name: 'Fogueira',        emoji: '🔥', color: '#ff6600', category: 'deco',   max: 5,  solid: false },
    { id: 'house',         name: 'Casa',            emoji: '🏠', color: '#d4c4a8', category: 'building', max: 10, solid: true },
    { id: 'building',      name: 'Prédio',          emoji: '🏢', color: '#888888', category: 'building', max: 8,  solid: true },
    { id: 'tower',         name: 'Torre',           emoji: '🗼', color: '#666677', category: 'building', max: 4,  solid: true },
    { id: 'car',           name: 'Carro',           emoji: '🚗', color: '#cc2222', category: 'vehicle', max: 8,  solid: true },
    { id: 'truck',         name: 'Camião',          emoji: '🚛', color: '#556b2f', category: 'vehicle', max: 5,  solid: true },
    { id: 'lamppost',      name: 'Farol',           emoji: '💡', color: '#ffffcc', category: 'deco',   max: 20, solid: false },
    { id: 'road',          name: 'Estrada',         emoji: '🛣️', color: '#333333', category: 'terrain', max: 99, solid: false },
    { id: 'bridge',        name: 'Ponte',           emoji: '🌉', color: '#8b6914', category: 'terrain', max: 10, solid: false },
    { id: 'wall_short',    name: 'Muro Baixo',      emoji: '🧱', color: '#888888', category: 'building', max: 30, solid: true },
    { id: 'sandbag',       name: 'Areia',           emoji: '🪖', color: '#8b7d5a', category: 'object', max: 20, solid: true },
    { id: 'crate_stack',   name: 'Caixas Empilhados',emoji: '📦', color: '#8B6914', category: 'object', max: 10, solid: true },
    { id: 'water_tower',   name: 'Torre de Água',   emoji: '🚰', color: '#445566', category: 'building', max: 4,  solid: true },
    { id: 'antenna',       name: 'Antena',          emoji: '📡', color: '#aaaaaa', category: 'deco',   max: 6,  solid: false },
  ],

  ZONE_THEMES: {
    forest:    { name: 'Floresta',     tiles: [0,1,0,0,1], ground: '#111c11' },
    city:      { name: 'Cidade',       tiles: [0,2,0,4,0], ground: '#1a1a1a' },
    enemy_base:{ name: 'Base Inimiga', tiles: [0,2,6,2,0], ground: '#1a1020' },
    volcano:   { name: 'Vulcão',       tiles: [6,2,6,0,2], ground: '#2a1510' },
    ocean:     { name: 'Oceano',       tiles: [3,0,3,0,5], ground: '#102040' },
    desert:    { name: 'Deserto',      tiles: [5,5,0,5,2], ground: '#c2a050' },
    mountains: { name: 'Montanhas',    tiles: [2,7,2,0,7], ground: '#8a9aa0' },
    battle_royale: { name: 'Battle Royale', tiles: [0,1,0,0,1,5], ground: '#1a2a12' },
  },

  TOOLS: {
    PAINT:   'paint',
    ERASE:   'erase',
    FILL:    'fill',
    PICK:    'pick',
    OBJECT:  'object',
    ERASE_OBJ: 'erase_obj',
  },

  MODES: {
    TILES:   'tiles',
    OBJECTS: 'objects',
  },
};
