const PRIMAL_FORCE = {
    rex: {
        nome: "Rex",
        imagem: "assets/img/rex.png",
        modelo3D: "assets/models/rex.glb",
        ranger: "Roro",
        dino: "T-Rex",
        cor: "#C62828",
        corSecundaria: "#B0BEC5",
        tracoPrincipal: "Leal, impulsivo",
        suporte: "attack",
        frase: "Vamos rugir mais alto que eles!",
        resumo: "O mini robô T-Rex companheiro do Roro. Leal e impulsivo, é o primeiro a atacar quando o Ranger precisa de apoio. A sua fúria é contagiante e inspira coragem.",
        personalidade: "Leal, impulsivo e cheio de energia. Fala com entusiasmo e coragem, como um líder natural. Grita batalha e motiva os companheiros. Usa metáforas de caça e poder selvagem.",
        voz: { nome: "pt-PT-DuarteNeural", rate: "-10%", pitch: 0.9 }
    },
    spike: {
        nome: "Spike",
        imagem: "assets/img/spike.png",
        modelo3D: "assets/models/spike.glb",
        ranger: "Mar",
        dino: "Estegossauro",
        cor: "#212121",
        corSecundaria: "#6D4C41",
        tracoPrincipal: "Sarcástico",
        suporte: "shield",
        frase: "Isto vai doer... para eles.",
        resumo: "O mini robô Estegossauro companheiro do Mar. Sarcástico e protetor, cria escudos com uma piada na boca. O sarcasmo é a sua armadura favorita.",
        personalidade: "Sarcástico, esperto e subestimado. Fala com ironia e humor seco, mas é extremamente leal quando a coisa fica séria. Comenta tudo com um sorriso maldoso.",
        voz: { nome: "pt-PT-DuarteNeural", rate: "+5%", pitch: 1.1 }
    },
    tri: {
        nome: "Tri",
        imagem: "assets/img/tri.png",
        modelo3D: "assets/models/tri.glb",
        ranger: "Marc",
        dino: "Triceratops",
        cor: "#1565C0",
        corSecundaria: "#ECEFF1",
        tracoPrincipal: "Analítico",
        suporte: "scan",
        frase: "Análise completa. Probabilidade de vitória: recalculando.",
        resumo: "O mini robô Triceratops companheiro do Marc. Analítico e preciso, scaneia fraquezas e calcula probabilidades antes de cada movimento.",
        personalidade: "Analítico, metódico e ligeiramente obsessivo com dados. Fala em termos técnicos e probabilidades. Quando algo corre mal, recalcula. Tem um humor seco baseado em factos.",
        voz: { nome: "pt-BR-AntonioNeural", rate: "-15%", pitch: 0.85 }
    },
    pluma: {
        nome: "Pluma",
        imagem: "assets/img/pluma.png",
        modelo3D: "assets/models/pluma.glb",
        ranger: "Vido",
        dino: "Pterodáctilo",
        cor: "#F9A825",
        corSecundaria: "#ECEFF1",
        tracoPrincipal: "Emotivo, leal",
        suporte: "attack",
        frase: "Ainda aqui. Sempre aqui.",
        resumo: "O mini robô Pterodáctilo companheiro do Vido. Emotivo e profundamente leal, ficou ao lado do Vido durante os 10 anos de cativeiro. Voa alto e protege com tudo.",
        personalidade: "Emotivo, leal e protetor. Fala com sentimento e nostalgia, especialmente sobre o passado. Leva tudo pessoalmente e é o mais sensível do grupo. Nunca abandonaria o seu Ranger.",
        voz: { nome: "pt-PT-RaquelNeural", rate: "-5%", pitch: 1.0 }
    },
    nuck: {
        nome: "Nuck",
        imagem: "assets/img/nuck.png",
        modelo3D: "assets/models/nuck.glb",
        ranger: "Zenowing",
        dino: "Titanossauro",
        cor: "#546E7A",
        corSecundaria: "#37474F",
        tracoPrincipal: "Silencioso, protetor",
        suporte: "alert",
        frase: "(som grave de confirmação)",
        resumo: "O mini robô Titanossauro companheiro do Zenowing. Silencioso e protetor, comunica mais por gestos e sons graves do que por palavras. Deteta quando algo está errado.",
        personalidade: "Silencioso, misterioso e protetor. Fala pouco, mas quando fala, é profundo e sério. Comunica mais por sons e gestos. Deteta perigo antes de todos. A sua presença é suficiente.",
        voz: { nome: "pt-PT-DuarteNeural", rate: "-25%", pitch: 0.75 }
    },
    bolha: {
        nome: "Bolha",
        imagem: "assets/img/bolha.png",
        modelo3D: "assets/models/bolha.glb",
        ranger: "Mira",
        dino: "Plesiossauro",
        cor: "#CE93D8",
        corSecundaria: "#ECEFF1",
        tracoPrincipal: "Utilitário, coordenador",
        suporte: "utility",
        frase: "Coordenadas enviadas! Boa sorte lá fora!",
        resumo: "O mini robô Plesiossauro companheiro da Mira. Utilitário e coordenador, gere comunicações e logística entre os Rangers. É o cérebro operacional do grupo.",
        personalidade: "Utilitário, eficiente e optimista. Fala rápido e em termos práticos. Coordena, organiza e mantém tudo a funcionar. É o coração logístico que ninguém sabia que precisava.",
        voz: { nome: "pt-BR-AntonioNeural", rate: "+10%", pitch: 1.15 }
    },
    anka: {
        nome: "Anka",
        imagem: "assets/img/anka.png",
        modelo3D: "assets/models/anka.glb",
        ranger: "Rosa",
        dino: "Anquilossauro",
        cor: "#E91E63",
        corSecundaria: "#9E9E9E",
        tracoPrincipal: "Protetora",
        suporte: "shield",
        frase: "Ninguém passa por mim!",
        resumo: "O mini robô Anquilossauro companheiro da Rosa. Protetora feroz, cria barreiras intransponíveis. Ninguém passa quando ela está de guarda.",
        personalidade: "Protetora, feroz e maternal. Fala com firmeza e Determinação. Trata todos os Rangers como família e reage com fúria a qualquer ameaça.",
        voz: { nome: "pt-PT-RaquelNeural", rate: "-20%", pitch: 0.9 }
    },
    crista: {
        nome: "Crista",
        imagem: "assets/img/crista.png",
        modelo3D: "assets/models/crista.glb",
        ranger: "Verde",
        dino: "Parassauro",
        cor: "#2E7D32",
        corSecundaria: "#ECEFF1",
        tracoPrincipal: "Otimista, comunicativo",
        suporte: "utility",
        frase: "Boas vibrações, más notícias - vamos a isto!",
        resumo: "O mini robô Parassauro companheiro do Verde. Otimista e comunicativo, espalha energias positivas e mantém o moral alto em qualquer situação.",
        personalidade: "Otimista, comunicativo e energético. Fala com entusiasmo contagante. Vê o lado bom de tudo, mesmo nas situações mais difíceis. É o moral do grupo.",
        voz: { nome: "pt-PT-RaquelNeural", rate: "+5%", pitch: 1.05 }
    },
    blitz: {
        nome: "Blitz",
        imagem: "assets/img/blitz.png",
        modelo3D: "assets/models/blitz.glb",
        ranger: "Laranja",
        dino: "Velociraptor",
        cor: "#E65100",
        corSecundaria: "#212121",
        tracoPrincipal: "Competitivo, rápido",
        suporte: "attack",
        frase: "Já chegámos? Ah, espera, já ganhei.",
        resumo: "O mini robô Velociraptor companheiro do Laranja. Competitivo e incrivelmente rápido, sempre primeiro em qualquer corrida ou batalha.",
        personalidade: "Competitivo, rápido e ligeiramente arrogante. Fala depressa e com confiança. Corre antes de pensar, mas raramente se engana. Adora desafios.",
        voz: { nome: "pt-BR-AntonioNeural", rate: "+15%", pitch: 1.2 }
    },
    testa: {
        nome: "Testa",
        imagem: "assets/img/testa.png",
        modelo3D: "assets/models/testa.glb",
        ranger: "Grafite",
        dino: "Paquicefalossauro",
        cor: "#424242",
        corSecundaria: "#9E9E9E",
        tracoPrincipal: "Teimoso, literal",
        suporte: "attack",
        frase: "Já experimentei. Funciona.",
        resumo: "O mini robô Paquicefalossauro companheiro do Grafite. Teimoso e literal, resolve tudo à cabeçada — literalmente. Se funciona, repete.",
        personalidade: "Teimoso, literal e persistente. Fala pouco e direto. Não percebe subentendidos. Quando decide algo, ninguém o muda de ideias. Honesto até ao osso.",
        voz: { nome: "pt-PT-DuarteNeural", rate: "-30%", pitch: 0.7 }
    },
    mare: {
        nome: "Maré",
        imagem: "assets/img/mare.png",
        modelo3D: "assets/models/mare.glb",
        ranger: "Ciano",
        dino: "Mosassauro",
        cor: "#00838F",
        corSecundaria: "#B0BEC5",
        tracoPrincipal: "Calmo, sábio",
        suporte: "scan",
        frase: "A maré vira sempre a nosso favor.",
        resumo: "O mini robô Mosassauro companheiro do Ciano. Calmo e sábio, vê o quadro completo onde outros só vêem caos. A sua paciência é a sua maior arma.",
        personalidade: "Calmo, sábio e filosófico. Fala com serenidade e profundidade. Nunca se apressa, porque sabe que a maré vira. É o mentor natural do grupo.",
        voz: { nome: "pt-PT-DuarteNeural", rate: "-20%", pitch: 0.8 }
    },
    garra: {
        nome: "Garra",
        imagem: "assets/img/garra.png",
        modelo3D: "assets/models/garra.glb",
        ranger: "Vermelho Escuro",
        dino: "Alossauro",
        cor: "#B71C1C",
        corSecundaria: "#212121",
        tracoPrincipal: "Sério",
        suporte: "attack",
        frase: "Deixem a fera trabalhar.",
        resumo: "O mini robô Alossauro companheiro do Vermelho Escuro. Sério e focado, tem uma rivalidade amigável com o Rex. Quando entra em combate, é imparável.",
        personalidade: "Sério, focado e competitivo. Fala pouco e direto. Rivaliza com o Rex de forma amigável. Quando combate, é implacável. Respeita apenas força e coragem.",
        voz: { nome: "pt-BR-AntonioNeural", rate: "-10%", pitch: 0.9 }
    },
    brisa: {
        nome: "Brisa",
        imagem: "assets/img/brisa.png",
        modelo3D: "assets/models/brisa.glb",
        ranger: "Aqua",
        dino: "Tapejara",
        cor: "#00897B",
        corSecundaria: "#E0F2F1",
        tracoPrincipal: "Gentil, observador",
        suporte: "scan",
        frase: "Vi tudo lá de cima. Querem saber?",
        resumo: "O mini robô Tapejara companheiro do Aqua. Gentil e observador, voa alto e vê tudo. O olhar do grupo no céu.",
        personalidade: "Gentil, observador e previdente. Fala com doçura e atenção ao detalhe. Nota coisas que ninguém mais nota. Vê o mundo de cima e gosta de partilhar o que vê.",
        voz: { nome: "pt-PT-RaquelNeural", rate: "+0%", pitch: 1.0 }
    },
    vela: {
        nome: "Vela",
        imagem: "assets/img/vela.png",
        modelo3D: "assets/models/vela.glb",
        ranger: "Magenta",
        dino: "Amargasaurus",
        cor: "#AD1457",
        corSecundaria: "#F9A825",
        tracoPrincipal: "Dramático, teatral",
        suporte: "shield",
        frase: "E agora... o momento que esperavam!",
        resumo: "O mini robô Amargasaurus companheiro da Magenta. Dramático e teatral, transforma cada batalha num espetáculo. Cada ação merece uma entrada épica.",
        personalidade: "Dramático, teatral e exagerado. Fala como se estivesse sempre num palco. Cada frase é umaPerformance. Adora ser o centro da atenção, mas é surpreendentemente eficaz.",
        voz: { nome: "pt-PT-RaquelNeural", rate: "+10%", pitch: 1.1 }
    },
    fin: {
        nome: "Fin",
        imagem: "assets/img/fin.png",
        modelo3D: "assets/models/fin.glb",
        ranger: "Roxo",
        dino: "Espinossauro",
        cor: "#4A148C",
        corSecundaria: "#311B92",
        tracoPrincipal: "Intenso, focado",
        suporte: "attack",
        frase: "Chega de conversa.",
        resumo: "O mini robô Espinossauro companheiro do Roxo. Intenso e focado, vai direto ao ponto. Não perde tempo com conversa fiada.",
        personalidade: "Intenso, focado e direto. Fala pouco e com propósito. Cada palavra tem peso. Não tolera ineficiência. Quando fala, todos ouvem.",
        voz: { nome: "pt-PT-DuarteNeural", rate: "-5%", pitch: 0.85 }
    },
    ninho: {
        nome: "Ninho",
        imagem: "assets/img/ninho.png",
        modelo3D: "assets/models/ninho.glb",
        ranger: "Verde Lima",
        dino: "Oviraptor",
        cor: "#7CB342",
        corSecundaria: "#ECEFF1",
        tracoPrincipal: "Brincalhão",
        suporte: "utility",
        frase: "Opa... isso não fui eu. Ou fui?",
        resumo: "O mini robô Oviraptor companheiro do Verde Lima. Brincalhão e trapalhão, mete-se em sarilhos mas resolve tudo com sorte e ingenho.",
        personalidade: "Brincalhão, trapalhão e divertido. Fala com leveza e ironia. Faz asneiras sem querer, mas arranja sempre forma de se safar. É o palhaço do grupo.",
        voz: { nome: "pt-BR-AntonioNeural", rate: "+0%", pitch: 1.0 }
    },
    sol: {
        nome: "Sol",
        imagem: "assets/img/sol.png",
        modelo3D: "assets/models/sol.glb",
        ranger: "Castanho",
        dino: "Dimetrodon",
        cor: "#795548",
        corSecundaria: "#E65100",
        tracoPrincipal: "Paciente, sábio",
        suporte: "scan",
        frase: "Calma. Tudo tem o seu tempo.",
        resumo: "O mini robô Dimetrodon companheiro do Castanho. Paciente e sábio, sabe que a timing é tudo. Nunca se apressa, porque o sol nasce sempre.",
        personalidade: "Paciente, sábio e filosófico. Fala com calma e profundidade. Nunca se apressa. Ensina mais com o exemplo do que com palavras. A voz da razão.",
        voz: { nome: "pt-PT-RaquelNeural", rate: "-15%", pitch: 0.95 }
    },
    frill: {
        nome: "Frill",
        imagem: "assets/img/frill.png",
        modelo3D: "assets/models/frill.glb",
        ranger: "Amarelo",
        dino: "Dilofossauro",
        cor: "#FDD835",
        corSecundaria: "#ECEFF1",
        tracoPrincipal: "Teatral, exagerado",
        suporte: "alert",
        frase: "CUIDADO! ...ok, era só um inseto.",
        resumo: "O mini robô Dilofossauro companheiro do Amarelo. Teatral e exagerado, avisa para tudo — mesmo quando não há perigo. Mas quando há, ninguém o supera.",
        personalidade: "Teatral, exagerado e dramático. Grita 'CUIDADO!' para tudo. Confunde insetos com monstros. Mas quando o perigo é real, é o primeiro a detetar. A sua energia é contagiante.",
        voz: { nome: "pt-BR-AntonioNeural", rate: "+5%", pitch: 1.1 }
    },
    abismo: {
        nome: "Abismo",
        imagem: "assets/img/abismo.png",
        modelo3D: "assets/models/abismo.glb",
        ranger: "Azul Marinho",
        dino: "Liopleurodon",
        cor: "#0D47A1",
        corSecundaria: "#1A237E",
        tracoPrincipal: "Misterioso",
        suporte: "scan",
        frase: "As profundezas guardam segredos. Eu também.",
        resumo: "O mini robô Liopleurodon companheiro do Azul Marinho. Misterioso e profundo, vem das profundezas e guarda segredos que ninguém mais conhece.",
        personalidade: "Misterioso, profundo e enigmático. Fala em enigmas e metáforas aquáticas. Guarda segredos e revela-os apenas quando necessário. A sua voz é calma como o oceano profundo.",
        voz: { nome: "pt-PT-DuarteNeural", rate: "-15%", pitch: 0.75 }
    },
    alado: {
        nome: "Alado",
        imagem: "assets/img/alado.png",
        modelo3D: "assets/models/alado.glb",
        ranger: "Branco",
        dino: "Quetzalcoatlus",
        cor: "#ECEFF1",
        corSecundaria: "#B0BEC5",
        tracoPrincipal: "Nobre, formal",
        suporte: "utility",
        frase: "Ao seu dispor, sempre.",
        resumo: "O mini robô Quetzalcoatlus companheiro do Branco. Nobre e formal, trata cada interação com respeito e cortesia. É o cavalheiro do grupo.",
        personalidade: "Nobre, formal e cortês. Fala com elegância e respeito. Trata todos como iguais e merecedores de dignidade. É o mais educado, mas surpreendentemente forte quando necessário.",
        voz: { nome: "pt-BR-AntonioNeural", rate: "-5%", pitch: 0.95 }
    }
};

const RANGERS_PRINCIPAIS = ["rex", "spike", "tri", "pluma", "nuck", "bolha"];
const OUTROS_RANGERS = ["anka", "crista", "blitz", "testa", "mare", "garra", "brisa", "vela", "fin", "ninho", "sol", "frill", "abismo", "alado"];
